'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Printers', [{
      printerid: "1",
      status: true,
      location: "H1",
      time: "6h-7h",
      slot: 10,
      name: "Máy in 1",
      type: "In thường",
    }, {
      printerid: "1",
      status: true,
      location: "H1",
      time: "7h-8h",
      slot: 10,
      name: "Máy in 1",
      type: "In thường",
    }, {
      printerid: "1",
      status: true,
      location: "H1",
      time: "8h-9h",
      slot: 10,
      name: "Máy in 1",
      type: "In thường",
    }, {
      printerid: "1",
      status: true,
      location: "H1",
      time: "9h-10",
      slot: 10,
      name: "Máy in 1",
      type: "In thường",
    }, {
      printerid: "1",
      status: true,
      location: "H1",
      time: "10h-11h",
      slot: 10,
      name: "Máy in 1",
      type: "In thường",
    }, {
      printerid: "1",
      status: true,
      location: "H1",
      time: "11h-12h",
      slot: 10,
      name: "Máy in 1",
      type: "In thường",
    }, {
      printerid: "1",
      status: true,
      location: "H1",
      time: "12h-13h",
      slot: 10,
      name: "Máy in 1",
      type: "In thường",
    }, {
      printerid: "1",
      status: true,
      location: "H1",
      time: "13h-14h",
      slot: 10,
      name: "Máy in 1",
      type: "In thường",
    }, {
      printerid: "1",
      status: true,
      location: "H1",
      time: "14h-15h",
      slot: 10,
      name: "Máy in 1",
      type: "In thường",
    }, {
      printerid: "1",
      status: true,
      location: "H1",
      time: "15h-16h",
      slot: 10,
      name: "Máy in 1",
      type: "In thường",
    }, {
      printerid: "1",
      status: true,
      location: "H1",
      time: "16h-17h",
      slot: 10,
      name: "Máy in 1",
      type: "In thường",
    }, {
      printerid: "1",
      status: true,
      location: "H1",
      time: "17h-18",
      slot: 10,
      name: "Máy in 1",
      type: "In thường",
    }, {
      printerid: "2",
      status: true,
      location: "H2",
      time: "6h-7h",
      slot: 10,
      name: "Máy in 2",
      type: "In thường",
    }, {
      printerid: "2",
      status: true,
      location: "H2",
      time: "7h-8h",
      slot: 10,
      name: "Máy in 2",
      type: "In thường",
    }, {
      printerid: "2",
      status: true,
      location: "H2",
      time: "8h-9h",
      slot: 10,
      name: "Máy in 2",
      type: "In thường",
    }, {
      printerid: "2",
      status: true,
      location: "H2",
      time: "9h-10",
      slot: 10,
      name: "Máy in 2",
      type: "In thường",
    }, {
      printerid: "2",
      status: true,
      location: "H2",
      time: "10h-11h",
      slot: 10,
      name: "Máy in 2",
      type: "In thường",
    }, {
      printerid: "2",
      status: true,
      location: "H2",
      time: "11h-12h",
      slot: 10,
      name: "Máy in 2",
      type: "In thường",
    }, {
      printerid: "2",
      status: true,
      location: "H2",
      time: "12h-13h",
      slot: 10,
      name: "Máy in 2",
      type: "In thường",
    }, {
      printerid: "2",
      status: true,
      location: "H2",
      time: "13h-14h",
      slot: 10,
      name: "Máy in 2",
      type: "In thường",
    }, {
      printerid: "2",
      status: true,
      location: "H2",
      time: "14h-15h",
      slot: 10,
      name: "Máy in 2",
      type: "In thường",
    }, {
      printerid: "2",
      status: true,
      location: "H2",
      time: "15h-16h",
      slot: 10,
      name: "Máy in 2",
      type: "In thường",
    }, {
      printerid: "2",
      status: true,
      location: "H2",
      time: "16h-17h",
      slot: 10,
      name: "Máy in 2",
      type: "In thường",
    }, {
      printerid: "2",
      status: true,
      location: "H2",
      time: "17h-18",
      slot: 10,
      name: "Máy in 2",
      type: "In thường",
    }, {
      printerid: "3",
      status: true,
      location: "H3",
      time: "6h-7h",
      slot: 10,
      name: "Máy in 3",
      type: "In thường",
    }, {
      printerid: "3",
      status: true,
      location: "H3",
      time: "7h-8h",
      slot: 10,
      name: "Máy in 3",
      type: "In thường",
    }, {
      printerid: "3",
      status: true,
      location: "H3",
      time: "8h-9h",
      slot: 10,
      name: "Máy in 3",
      type: "In thường",
    }, {
      printerid: "3",
      status: true,
      location: "H3",
      time: "9h-10",
      slot: 10,
      name: "Máy in 3",
      type: "In thường",
    }, {
      printerid: "3",
      status: true,
      location: "H3",
      time: "10h-11h",
      slot: 10,
      name: "Máy in 3",
      type: "In thường",
    }, {
      printerid: "3",
      status: true,
      location: "H3",
      time: "11h-12h",
      slot: 10,
      name: "Máy in 3",
      type: "In thường",
    }, {
      printerid: "3",
      status: true,
      location: "H3",
      time: "12h-13h",
      slot: 10,
      name: "Máy in 3",
      type: "In thường",
    }, {
      printerid: "3",
      status: true,
      location: "H3",
      time: "13h-14h",
      slot: 10,
      name: "Máy in 3",
      type: "In thường",
    }, {
      printerid: "3",
      status: true,
      location: "H3",
      time: "14h-15h",
      slot: 10,
      name: "Máy in 3",
      type: "In thường",
    }, {
      printerid: "3",
      status: true,
      location: "H3",
      time: "15h-16h",
      slot: 10,
      name: "Máy in 3",
      type: "In thường",
    }, {
      printerid: "3",
      status: true,
      location: "H3",
      time: "16h-17h",
      slot: 10,
      name: "Máy in 3",
      type: "In thường",
    }, {
      printerid: "3",
      status: true,
      location: "H3",
      time: "17h-18",
      slot: 10,
      name: "Máy in 3",
      type: "In thường",
    }, {
      printerid: "4",
      status: true,
      location: "H6",
      time: "6h-7h",
      slot: 10,
      name: "Máy in 4",
      type: "In thường",
    }, {
      printerid: "4",
      status: true,
      location: "H6",
      time: "7h-8h",
      slot: 10,
      name: "Máy in 4",
      type: "In thường",
    }, {
      printerid: "4",
      status: true,
      location: "H6",
      time: "8h-9h",
      slot: 10,
      name: "Máy in 4",
      type: "In thường",
    }, {
      printerid: "4",
      status: true,
      location: "H6",
      time: "9h-10",
      slot: 10,
      name: "Máy in 4",
      type: "In thường",
    }, {
      printerid: "4",
      status: true,
      location: "H6",
      time: "10h-11h",
      slot: 10,
      name: "Máy in 4",
      type: "In thường",
    }, {
      printerid: "4",
      status: true,
      location: "H6",
      time: "11h-12h",
      slot: 10,
      name: "Máy in 4",
      type: "In thường",
    }, {
      printerid: "4",
      status: true,
      location: "H6",
      time: "12h-13h",
      slot: 10,
      name: "Máy in 4",
      type: "In thường",
    }, {
      printerid: "4",
      status: true,
      location: "H6",
      time: "13h-14h",
      slot: 10,
      name: "Máy in 4",
      type: "In thường",
    }, {
      printerid: "4",
      status: true,
      location: "H6",
      time: "14h-15h",
      slot: 10,
      name: "Máy in 4",
      type: "In thường",
    }, {
      printerid: "4",
      status: true,
      location: "H6",
      time: "15h-16h",
      slot: 10,
      name: "Máy in 4",
      type: "In thường",
    }, {
      printerid: "4",
      status: true,
      location: "H6",
      time: "16h-17h",
      slot: 10,
      name: "Máy in 4",
      type: "In thường",
    }, {
      printerid: "4",
      status: true,
      location: "H6",
      time: "17h-18",
      slot: 10,
      name: "Máy in 4",
      type: "In thường",
    }, {
      printerid: "5",
      status: true,
      location: "H1",
      time: "6h-7h",
      slot: 10,
      name: "Máy in 5",
      type: "In màu",
    }, {
      printerid: "5",
      status: true,
      location: "H1",
      time: "7h-8h",
      slot: 10,
      name: "Máy in 5",
      type: "In màu",
    }, {
      printerid: "5",
      status: true,
      location: "H1",
      time: "8h-9h",
      slot: 10,
      name: "Máy in 5",
      type: "In màu",
    }, {
      printerid: "5",
      status: true,
      location: "H1",
      time: "9h-10",
      slot: 10,
      name: "Máy in 5",
      type: "In màu",
    }, {
      printerid: "5",
      status: true,
      location: "H5",
      time: "10h-11h",
      slot: 10,
      name: "Máy in 5",
      type: "In màu",
    }, {
      printerid: "5",
      status: true,
      location: "H1",
      time: "11h-12h",
      slot: 10,
      name: "Máy in 5",
      type: "In màu",
    }, {
      printerid: "5",
      status: true,
      location: "H1",
      time: "12h-13h",
      slot: 10,
      name: "Máy in 5",
      type: "In màu",
    }, {
      printerid: "5",
      status: true,
      location: "H1",
      time: "13h-14h",
      slot: 10,
      name: "Máy in 5",
      type: "In màu",
    }, {
      printerid: "5",
      status: true,
      location: "H1",
      time: "14h-15h",
      slot: 10,
      name: "Máy in 5",
      type: "In màu",
    }, {
      printerid: "5",
      status: true,
      location: "H1",
      time: "15h-16h",
      slot: 10,
      name: "Máy in 5",
      type: "In màu",
    }, {
      printerid: "5",
      status: true,
      location: "H1",
      time: "16h-17h",
      slot: 10,
      name: "Máy in 5",
      type: "In màu",
    }, {
      printerid: "5",
      status: true,
      location: "H1",
      time: "17h-18",
      slot: 10,
      name: "Máy in 5",
      type: "In màu",
    }, {
      printerid: "6",
      status: true,
      location: "H2",
      time: "6h-7h",
      slot: 10,
      name: "Máy in 6",
      type: "In màu",
    }, {
      printerid: "6",
      status: true,
      location: "H2",
      time: "7h-8h",
      slot: 10,
      name: "Máy in 6",
      type: "In màu",
    }, {
      printerid: "6",
      status: true,
      location: "H2",
      time: "8h-9h",
      slot: 10,
      name: "Máy in 6",
      type: "In màu",
    }, {
      printerid: "6",
      status: true,
      location: "H2",
      time: "9h-10",
      slot: 10,
      name: "Máy in 6",
      type: "In màu",
    }, {
      printerid: "6",
      status: true,
      location: "H2",
      time: "10h-11h",
      slot: 10,
      name: "Máy in 6",
      type: "In màu",
    }, {
      printerid: "6",
      status: true,
      location: "H2",
      time: "11h-12h",
      slot: 10,
      name: "Máy in 6",
      type: "In màu",
    }, {
      printerid: "6",
      status: true,
      location: "H2",
      time: "12h-13h",
      slot: 10,
      name: "Máy in 6",
      type: "In màu",
    }, {
      printerid: "6",
      status: true,
      location: "H2",
      time: "13h-14h",
      slot: 10,
      name: "Máy in 6",
      type: "In màu",
    }, {
      printerid: "6",
      status: true,
      location: "H2",
      time: "14h-15h",
      slot: 10,
      name: "Máy in 6",
      type: "In màu",
    }, {
      printerid: "6",
      status: true,
      location: "H2",
      time: "15h-16h",
      slot: 10,
      name: "Máy in 6",
      type: "In màu",
    }, {
      printerid: "6",
      status: true,
      location: "H2",
      time: "16h-17h",
      slot: 10,
      name: "Máy in 6",
      type: "In màu",
    }, {
      printerid: "6",
      status: true,
      location: "H2",
      time: "17h-18",
      slot: 10,
      name: "Máy in 6",
      type: "In màu",
    },], {});
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
